### PR TITLE
Several fixes for CI

### PR DESCRIPTION
**Pull request by DilumAluthge**
1. Test on the 1.6 beta
2. Split the Julia nightly testing into a separate workflow file
3. Fix the docs build
4. Set a timeout of 30 minutes per job. (We can always increase this. I put this in because some of the jobs are timing out at 6 hours, which ends up wasting CI time.)

### CODE REVIEW

**Comment by chriselrod** [comment]
>     4\. Set a timeout of 30 minutes per job. (We can always increase this. I put this in because some of the jobs are timing out at 6 hours, which ends up wasting CI time.)

More likely we should shorten it, because of they don't finish very quickly, it probably got stuck and will never finish.
Seems to suggest there is a bug.

**Comment by DilumAluthge** [comment]
> > ```
> > 4\. Set a timeout of 30 minutes per job. (We can always increase this. I put this in because some of the jobs are timing out at 6 hours, which ends up wasting CI time.)
> > ```
> 
> More likely we should shorten it, because of they don't finish very quickly, it probably got stuck and will never finish.
> Seems to suggest there is a bug.

I've shortened it to 10 minutes.

**Comment by chriselrod** [comment]
I'll go ahead and merge this to waste less CI time.
I'll have to see went it's failing. I've not had it get stuck locally.

I'll probably have to add counters with asserts in a few loops to try and get error messages on CI.

**Comment by DilumAluthge** [comment]
> I'll go ahead and merge this to waste less CI time.

Yeah, the GitHub Actions global concurrency limit of 20 simultaneous jobs applies to all repositories on your account, so if jobs time out to 6 hours, it'll slow down the CI on all of your repos.

**Pull request merged**
