### PR TITLE
Print `versioninfo` at the beginning of the test suite, and add a bunch of debugging statements

### PR DESCRIPTION
**Pull request by DilumAluthge**
On the off chance that the timeouts are due to something specific about the machine.

### CODE REVIEW

**Comment by chriselrod** [comment]
All green. =)
Tests passed in my draft PR too, as well as on master.
I think moving the initial setting-the-state-to-`SPIN` into the `(::ThreadTask)` helped.

So I'm inclined to issue a release of `ThreadingUtilities`, set Octavian's lower bound to `0.1.1` in the PR, merge it.

In a few hours, my [Optim.optimize(...)](https://github.com/chriselrod/StrideArrays.jl/blob/c30c445f26960f9d9f952b6be1308e26d6c6e432/benchmark/tilesearch.jl#L243) should finish, and I'll update the default parameters in Octavian accordingly, and run small, medium, and large size benchmarks with OpenBLAS, MKL, BLIS, Gaius, Tullio, and Octavian.

**Comment by DilumAluthge** [comment]
Just FYI I think there are some other test failures in the Octavian PR that are not related to ThreadingUtilities.

**Comment by chriselrod** [comment]
Tests passed locally. I'll rerun them before merging.

**Comment by chriselrod** [comment]
That was before, now
```julia
julia> using Octavian
[ Info: Precompiling Octavian [6fd5a793-0b7e-452c-907f-f8bfe9c57db4]
ERROR: LoadError: InitError: Evaluation into the closed module `ThreadingUtilities` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `ThreadingUtilities` with `eval` during precompilation - don't do this.
```

**Comment by chriselrod** [comment]
I'm guessing the `@eval` inside the `__init__` is problematic. I'll replace the tuple of `Ref`s with a `Vector{UInt}`.

**Comment by chriselrod** [comment]
Just confirming:
```julia
Test Summary:         | Pass  Total
Matrix Multiply Int64 | 2744   2744
 25.108892 seconds (639.47 k allocations: 3.268 GiB, 4.93% gc time)
     Testing Octavian tests passed
```

**Pull request closed without merging**
