### PR TITLE
THREADPOOL: Use the runtime value of `Sys.CPU_THREADS`

### LINKED ISSUE #4: ThreadingUtilities.jl is currently not relocatable
Consider this line:

https://github.com/chriselrod/ThreadingUtilities.jl/blob/23434f69c8712d2388088a24abcf9b3a071bfa07/src/threadtasks.jl#L6-L6

This line is evaluated at precompile time. Unfortunately, this means that if you precompile ThreadingUtilities.jl on one machine, you cannot then use it on a different machine with a different value for `Sys.CPU_THREADS`.

In other words, this line makes ThreadingUtilities not relocatable.

So, for example, you cannot use PackageCompiler.jl to make a relocatable app that uses ThreadingUtilities.

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #4

### CODE REVIEW

**Comment by chriselrod** [comment]
What does `@code_warntype taskpointer(1)` and `@codetyped task pointer(1)` look like before and after?

**Comment by DilumAluthge** [comment]
> What does `@code_warntype taskpointer(1)` and `@codetyped task pointer(1)` look like before and after?

Good question. One sec, I'll run it.

**Comment by DilumAluthge** [comment]
With `ThreadingUtilities#master`:

```julia
julia> using ThreadingUtilities

julia> @code_warntype ThreadingUtilities.taskpointer(1)
Variables
  #self#::Core.Const(ThreadingUtilities.taskpointer)
  tid::Int64

Body::Ptr{UInt64}
1 ─      nothing
│   %2 = Base.getindex(ThreadingUtilities.THREADPOOL, tid)::ThreadingUtilities.ThreadTask
│   %3 = ThreadingUtilities.pointer(%2)::Ptr{UInt64}
└──      return %3
```
```julia
julia> using ThreadingUtilities

julia> @code_typed ThreadingUtilities.taskpointer(1)
CodeInfo(
1 ─ %1 = ThreadingUtilities.THREADPOOL::Core.Const((ThreadingUtilities.ThreadTask(Base.RefValue{NTuple{32, UInt64}}((0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000))), ThreadingUtilities.ThreadTask(Base.RefValue{NTuple{32, UInt64}}((0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000))), ThreadingUtilities.ThreadTask(Base.RefValue{NTuple{32, UInt64}}((0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000)))))
│   %2 = Base.getfield(%1, tid, $(Expr(:boundscheck)))::ThreadingUtilities.ThreadTask
│   %3 = Base.getfield(%2, :memory)::Base.RefValue{NTuple{32, UInt64}}
│   %4 = $(Expr(:foreigncall, :(:jl_value_ptr), Ptr{Nothing}, svec(Any), 0, :(:ccall), :(%3)))::Ptr{Nothing}
│   %5 = Base.bitcast(Ptr{UInt64}, %4)::Ptr{UInt64}
└──      return %5
) => Ptr{UInt64}
```

With `https://github.com/DilumAluthge/ThreadingUtilities.jl#dpa/relocatable`:

```julia
julia> using ThreadingUtilities

julia> @code_warntype ThreadingUtilities.taskpointer(1)
Variables
  #self#::Core.Const(ThreadingUtilities.taskpointer)
  tid::Int64

Body::Ptr{UInt64}
1 ─      nothing
│   %2 = Base.getindex(ThreadingUtilities.THREADPOOL, tid)::ThreadingUtilities.ThreadTask
│   %3 = ThreadingUtilities.pointer(%2)::Ptr{UInt64}
└──      return %3
```

```julia
julia> using ThreadingUtilities

julia> @code_typed ThreadingUtilities.taskpointer(1)
CodeInfo(
1 ─ %1 = ThreadingUtilities.THREADPOOL::Core.Const((ThreadingUtilities.ThreadTask(Base.RefValue{NTuple{32, UInt64}}((0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000))), ThreadingUtilities.ThreadTask(Base.RefValue{NTuple{32, UInt64}}((0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000))), ThreadingUtilities.ThreadTask(Base.RefValue{NTuple{32, UInt64}}((0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000)))))
│   %2 = Base.getfield(%1, tid, $(Expr(:boundscheck)))::ThreadingUtilities.ThreadTask
│   %3 = Base.getfield(%2, :memory)::Base.RefValue{NTuple{32, UInt64}}
│   %4 = $(Expr(:foreigncall, :(:jl_value_ptr), Ptr{Nothing}, svec(Any), 0, :(:ccall), :(%3)))::Ptr{Nothing}
│   %5 = Base.bitcast(Ptr{UInt64}, %4)::Ptr{UInt64}
└──      return %5
) => Ptr{UInt64}
```

**Comment by DilumAluthge** [comment]
Some of the lines in the `@code_typed` output is really long. You'll need to scroll pretty far to the right to see it all.

**Comment by chriselrod** [comment]
Great, I was worried it being defined later would cause problems.

**Pull request merged**
